Joining the dataframes
condition---there should be a common field

syntax:
    merge(df1, df2, on='player_name', how = 'inner')

In [2]:
import pandas as pd

In [3]:
df1 = pd.DataFrame({
    'Player Name' : ['Rahul Dravid', 'Sachin Tendulkar', 'Virat Kohli', 'Ricky Ponting', 'M.S. Dhoni'],
    'Age' : [48, 50, 34, 42, 40],
})
df1

        Player Name  Age
0      Rahul Dravid   48
1  Sachin Tendulkar   50
2       Virat Kohli   34
3     Ricky Ponting   42
4        M.S. Dhoni   40

In [4]:
df2 = pd.DataFrame({
    'Player Name' : ['Rahul Dravid', 'Sachin Tendulkar', 'Virat Kohli', 'Hardik Pandya', 'M.S. Dhoni'],
    'salary' : [1000000, 500000, 2000000, 1500000, 2500000]
})

df2

        Player Name   salary
0      Rahul Dravid  1000000
1  Sachin Tendulkar   500000
2       Virat Kohli  2000000
3     Hardik Pandya  1500000
4        M.S. Dhoni  2500000

In [5]:
# inner join
pd.merge(df1, df2, on = 'Player Name', how = 'inner')

        Player Name  Age   salary
0      Rahul Dravid   48  1000000
1  Sachin Tendulkar   50   500000
2       Virat Kohli   34  2000000
3        M.S. Dhoni   40  2500000

In [6]:
# left join
pd.merge(df1, df2, on = 'Player Name', how = 'left')

        Player Name  Age     salary
0      Rahul Dravid   48  1000000.0
1  Sachin Tendulkar   50   500000.0
2       Virat Kohli   34  2000000.0
3     Ricky Ponting   42        NaN
4        M.S. Dhoni   40  2500000.0

In [7]:
# right join
pd.merge(df1, df2, on = 'Player Name', how = 'right')

        Player Name   Age   salary
0      Rahul Dravid  48.0  1000000
1  Sachin Tendulkar  50.0   500000
2       Virat Kohli  34.0  2000000
3     Hardik Pandya   NaN  1500000
4        M.S. Dhoni  40.0  2500000

In [ ]:
# outer join : means union of left and right join
pd.merge(df1, df2, on = 'Player Name', how = 'outer')

        Player Name   Age     salary
0     Hardik Pandya   NaN  1500000.0
1        M.S. Dhoni  40.0  2500000.0
2      Rahul Dravid  48.0  1000000.0
3     Ricky Ponting  42.0        NaN
4  Sachin Tendulkar  50.0   500000.0
5       Virat Kohli  34.0  2000000.0

In [12]:
df3 = pd.DataFrame({
    'Player Name' : ['Rahul Dravid', 'Sachin Tendulkar', 'Virat Kohli', 'Ricky Ponting', 'M.S. Dhoni'],
    'Age' : [48, 50, 34, 42, 40],
})
df3

        Player Name  Age
0      Rahul Dravid   48
1  Sachin Tendulkar   50
2       Virat Kohli   34
3     Ricky Ponting   42
4        M.S. Dhoni   40

In [13]:
df4 = pd.DataFrame({
    'Sports Person' : ['Rahul Dravid', 'Sachin Tendulkar', 'Virat Kohli', 'Hardik Pandya', 'M.S. Dhoni'],
    'salary' : [1000000, 500000, 2000000, 1500000, 2500000]
})

df4

      Sports Person   salary
0      Rahul Dravid  1000000
1  Sachin Tendulkar   500000
2       Virat Kohli  2000000
3     Hardik Pandya  1500000
4        M.S. Dhoni  2500000

In [ ]:
# Join Dataframes even when two DF have diffrant col name
pd.merge(df3, df4, left_on = 'Player Name', right_on = 'Sports Person', how = 'inner')

        Player Name  Age     Sports Person   salary
0      Rahul Dravid   48      Rahul Dravid  1000000
1  Sachin Tendulkar   50  Sachin Tendulkar   500000
2       Virat Kohli   34       Virat Kohli  2000000
3        M.S. Dhoni   40        M.S. Dhoni  2500000

In [18]:
pd.concat([df3, df4], ignore_index = True)

        Player Name   Age     Sports Person     salary
0      Rahul Dravid  48.0               NaN        NaN
1  Sachin Tendulkar  50.0               NaN        NaN
2       Virat Kohli  34.0               NaN        NaN
3     Ricky Ponting  42.0               NaN        NaN
4        M.S. Dhoni  40.0               NaN        NaN
5               NaN   NaN      Rahul Dravid  1000000.0
6               NaN   NaN  Sachin Tendulkar   500000.0
7               NaN   NaN       Virat Kohli  2000000.0
8               NaN   NaN     Hardik Pandya  1500000.0
9               NaN   NaN        M.S. Dhoni  2500000.0

In [19]:
pd.concat([df3, df4], axis=1)

        Player Name  Age     Sports Person   salary
0      Rahul Dravid   48      Rahul Dravid  1000000
1  Sachin Tendulkar   50  Sachin Tendulkar   500000
2       Virat Kohli   34       Virat Kohli  2000000
3     Ricky Ponting   42     Hardik Pandya  1500000
4        M.S. Dhoni   40        M.S. Dhoni  2500000