In [1]:
import pandas as pd

In [5]:
df = pd.read_csv(r"C:\Users\HP\Desktop\pandas\Dataset\titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df.iloc[5,3]

'Moran, Mr. James'

In [11]:
df.iloc[5:10, 0:4]

,PassengerId,Survived,Pclass,Name
5,6,0,3,"Moran, Mr. James"
6,7,0,1,"McCarthy, Mr. Timothy J"
7,8,0,3,"Palsson, Master. Gosta Leonard"
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)"
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)"

In [12]:
df.iloc[:,4]

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: object

In [21]:
#  i want to display whos age is greater than 30 and sex is male
df[(df['Age'] > 30) & (df['Sex'] == 'male')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
...,...,...,...,...,...,...,...,...,...,...,...,...
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [22]:
df[(df['Age'] > 30) & (df['Sex'] == 'male')] [['Name', 'Age']]

                                     Name   Age
4                Allen, Mr. William Henry  35.0
6                 McCarthy, Mr. Timothy J  54.0
13            Andersson, Mr. Anders Johan  39.0
20                   Fynney, Mr. Joseph J  35.0
21                  Beesley, Mr. Lawrence  34.0
..                                    ...   ...
867  Roebling, Mr. Washington Augustus II  31.0
872              Carlsson, Mr. Frans Olof  33.0
873           Vander Cruyssen, Mr. Victor  47.0
881                    Markun, Mr. Johann  33.0
890                   Dooley, Mr. Patrick  32.0

[202 rows x 2 columns]

In [29]:
# only display female name
df[(df['Sex'] == 'female')] [['Name', 'Survived']]

                                                  Name  Survived
1    Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                               Heikkinen, Miss. Laina         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)         1
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         1
9                  Nasser, Mrs. Nicholas (Adele Achem)         1
..                                                 ...       ...
880       Shelley, Mrs. William (Imanita Parrish Hall)         1
882                       Dahlberg, Miss. Gerda Ulrika         0
885               Rice, Mrs. William (Margaret Norton)         0
887                       Graham, Miss. Margaret Edith         1
888           Johnston, Miss. Catherine Helen "Carrie"         0

[314 rows x 2 columns]

Where method

In [30]:
import numpy as np

In [32]:
df = pd.DataFrame(data = np.random.randint(0, 100, (4,3)),
columns = ('Test1', 'Test2', 'Test3'),
index = ['Vinay', 'Tushar', 'Ajay', 'Kartik'])


df

        Test1  Test2  Test3
Vinay      77     58     44
Tushar     33     62     97
Ajay       51     90     98
Kartik     42      3     26

In [33]:
# if marks are greater than 70 or 80 replace those marks with A+ grade
df.where(df <= 70, 'A+')

       Test1 Test2 Test3
Vinay     A+    58    44
Tushar    33    62    A+
Ajay      51    A+    A+
Kartik    42     3    26

In [36]:
df.where(df['Test3'] >= 30, 'Bad')

       Test1 Test2 Test3
Vinay     77    58    44
Tushar    33    62    97
Ajay      51    90    98
Kartik   Bad   Bad   Bad

In [38]:
# where narks = 40 diplay medium marks
df.where(df != 40, 'Medium')

        Test1  Test2  Test3
Vinay      77     58     44
Tushar     33     62     97
Ajay       51     90     98
Kartik     42      3     26

In [ ]:
#  using lambda
df.where(lambda x : x != 26, 'Medium')

        Test1  Test2   Test3
Vinay      77     58      44
Tushar     33     62      97
Ajay       51     90      98
Kartik     42      3  Medium

In [40]:
df1 = pd.DataFrame(data = np.random.randint(0, 100, (4,3)),
columns = ('Test1', 'Test2', 'Test3'),
index = ['Vinay', 'Tushar', 'Ajay', 'Kartik'])


df1

        Test1  Test2  Test3
Vinay      99     32     95
Tushar     94     41     70
Ajay       11     77     55
Kartik     16     22     45

In [42]:
# replacing the val based on cond from df to df1
df1.where(df <= 80, df1)

        Test1  Test2  Test3
Vinay      99     32     95
Tushar     94     41     70
Ajay       11     77     55
Kartik     16     22     45

In [ ]:
df1.where(df <= 80, df + df1)

        Test1  Test2  Test3
Vinay      99     32     95
Tushar     94     41    167
Ajay       11    167    153
Kartik     16     22     45