In [8]:
import pandas as pd

In [13]:
df = pd.read_csv(
    r'C:\Users\HP\Desktop\Python-Assignments\Dataset\textdata.txt',
    sep=r'\s+',
    names=['A', 'B', 'C', 'Person']
)

In [14]:
df

   A  B      C   Person
0  1  1   2.92    Vijay
1  1  2  70.75    Kumar
2  1  3  60.90    Vinay
3  2  1  71.34     Anil
4  2  2   5.23    Ashok
5  2  3  38.56   Neeraj
6  3  1  61.24     Sita
7  3  2  38.68    Laxmi
8  3  3   4.49  Chandra

In [17]:
df = pd.read_csv(r'C:\Users\HP\Desktop\Python-Assignments\Dataset\empdata.csv')
df

   empid           ename       sal         doj
0   1001      Ganesh Rao  10000.00  2000-10-10
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10
5   1006       Anant Nag   9999.99  1999-09-09

loc, iloc

In [19]:
df.loc[:,'ename']

0        Ganesh Rao
1        Anil Kumar
2      Gaurav Gupta
3      Hema Chandra
4    Laxmi Prasanna
5         Anant Nag
Name: ename, dtype: object

In [22]:
df.iloc[:,1]

0        Ganesh Rao
1        Anil Kumar
2      Gaurav Gupta
3      Hema Chandra
4    Laxmi Prasanna
5         Anant Nag
Name: ename, dtype: object

In [24]:
# to see more than one col
df.loc[:, ['ename', 'sal']]

            ename       sal
0      Ganesh Rao  10000.00
1      Anil Kumar  23000.50
2    Gaurav Gupta  18000.33
3    Hema Chandra  16500.50
4  Laxmi Prasanna  12000.75
5       Anant Nag   9999.99

In [25]:
df.iloc[:, [1,2]]

            ename       sal
0      Ganesh Rao  10000.00
1      Anil Kumar  23000.50
2    Gaurav Gupta  18000.33
3    Hema Chandra  16500.50
4  Laxmi Prasanna  12000.75
5       Anant Nag   9999.99

In [27]:
# to see range rows
df.loc[0:3, ['ename', 'sal']]

          ename       sal
0    Ganesh Rao  10000.00
1    Anil Kumar  23000.50
2  Gaurav Gupta  18000.33
3  Hema Chandra  16500.50

In [28]:
df.iloc[0:3, [1,2]]

          ename       sal
0    Ganesh Rao  10000.00
1    Anil Kumar  23000.50
2  Gaurav Gupta  18000.33

In [31]:
# to display last row
df.iloc[-1]

empid          1006
ename     Anant Nag
sal         9999.99
doj      1999-09-09
Name: 5, dtype: object

In [32]:
# retirive last col
df.loc[:, 'doj']

0    2000-10-10
1    2002-03-03
2    2002-03-03
3    2002-03-03
4    2000-08-10
5    1999-09-09
Name: doj, dtype: object

In [33]:
df.iloc[:, -1]

0    2000-10-10
1    2002-03-03
2    2002-03-03
3    2002-03-03
4    2000-08-10
5    1999-09-09
Name: doj, dtype: object

basic opration

In [35]:
df.shape

(6, 4)

In [36]:
df.head()

   empid           ename       sal         doj
0   1001      Ganesh Rao  10000.00  2000-10-10
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10

In [37]:
df.tail(2)

   empid           ename       sal         doj
4   1005  Laxmi Prasanna  12000.75  2000-08-10
5   1006       Anant Nag   9999.99  1999-09-09

In [39]:
df.columns

Index(['empid', 'ename', 'sal', 'doj'], dtype='object')

In [40]:
df[2:5]

   empid           ename       sal         doj
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10

In [41]:
# alternate rows
df[::2]

   empid           ename       sal         doj
0   1001      Ganesh Rao  10000.00  2000-10-10
2   1003    Gaurav Gupta  18000.33  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10

In [42]:
# dispaly rows revrse manner
df[::-1]

   empid           ename       sal         doj
5   1006       Anant Nag   9999.99  1999-09-09
4   1005  Laxmi Prasanna  12000.75  2000-08-10
3   1004    Hema Chandra  16500.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
1   1002      Anil Kumar  23000.50  2002-03-03
0   1001      Ganesh Rao  10000.00  2000-10-10

In [44]:
# alternate rows with col
df[::2][['ename', 'doj']]

            ename         doj
0      Ganesh Rao  2000-10-10
2    Gaurav Gupta  2002-03-03
4  Laxmi Prasanna  2000-08-10

In [45]:
df

   empid           ename       sal         doj
0   1001      Ganesh Rao  10000.00  2000-10-10
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10
5   1006       Anant Nag   9999.99  1999-09-09

In [46]:
# to know the max sal
df.sal.max()

np.float64(23000.5)

In [47]:
df['sal'].max()

np.float64(23000.5)

In [50]:
df['sal'].mean()

np.float64(14917.011666666667)

In [49]:
# avg sal
print('Average sal= ',df['sal'].mean())

Average sal=  14917.011666666667

In [51]:
#  to print stastical info
df.describe()

             empid           sal
count     6.000000      6.000000
mean   1003.500000  14917.011667
std       1.870829   5181.037711
min    1001.000000   9999.990000
25%    1002.250000  10500.187500
50%    1003.500000  14250.625000
75%    1004.750000  17625.372500
max    1006.000000  23000.500000

Conditions

In [55]:

df[df['sal']>10000]

   empid           ename       sal         doj
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10

In [58]:
df[(df['sal']>10000) & (df.sal<20000)]

   empid           ename       sal         doj
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10

In [63]:
df.set_index('empid', inplace=True)
df

                ename       sal         doj
empid
1001       Ganesh Rao  10000.00  2000-10-10
1002       Anil Kumar  23000.50  2002-03-03
1003     Gaurav Gupta  18000.33  2002-03-03
1004     Hema Chandra  16500.50  2002-03-03
1005   Laxmi Prasanna  12000.75  2000-08-10
1006        Anant Nag   9999.99  1999-09-09

In [64]:
df.reset_index('empid', inplace=True)
df

   empid           ename       sal         doj
0   1001      Ganesh Rao  10000.00  2000-10-10
1   1002      Anil Kumar  23000.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
3   1004    Hema Chandra  16500.50  2002-03-03
4   1005  Laxmi Prasanna  12000.75  2000-08-10
5   1006       Anant Nag   9999.99  1999-09-09

sorting

In [66]:
# desc order
df.sort_values('ename', ascending=False)

   empid           ename       sal         doj
4   1005  Laxmi Prasanna  12000.75  2000-08-10
3   1004    Hema Chandra  16500.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
0   1001      Ganesh Rao  10000.00  2000-10-10
1   1002      Anil Kumar  23000.50  2002-03-03
5   1006       Anant Nag   9999.99  1999-09-09

In [67]:
df.sort_values(by=['doj', 'sal'], ascending=[False, True])

   empid           ename       sal         doj
3   1004    Hema Chandra  16500.50  2002-03-03
2   1003    Gaurav Gupta  18000.33  2002-03-03
1   1002      Anil Kumar  23000.50  2002-03-03
0   1001      Ganesh Rao  10000.00  2000-10-10
4   1005  Laxmi Prasanna  12000.75  2000-08-10
5   1006       Anant Nag   9999.99  1999-09-09