window -> one or more col of a df,
window func -> time series

In [2]:
import pandas as pd
import numpy as np

In [6]:
df = pd.DataFrame({
    'a': [1, 2, 34, 5, 6, 7, 8],
    'b': [10, np.nan, np.nan, 20, np.nan, np.nan, 30]
})

print(df)

    a     b
0   1  10.0
1   2   NaN
2  34   NaN
3   5  20.0
4   6   NaN
5   7   NaN
6   8  30.0

In [ ]:
# find cummulative sum of the col 'a'
df['a_cumsum'] = df['a'].cumsum()
df

    a     b  a_cumsum
0   1  10.0         1
1   2   NaN         3
2  34   NaN        37
3   5  20.0        42
4   6   NaN        48
5   7   NaN        55
6   8  30.0        63

In [8]:
# cummu prod of 'a'
df['a_cumsum'] = df['a'].cumprod()
df

    a     b  a_cumsum
0   1  10.0         1
1   2   NaN         2
2  34   NaN        68
3   5  20.0       340
4   6   NaN      2040
5   7   NaN     14280
6   8  30.0    114240