In [2]:
import pandas as pd

In [3]:
cust = pd.read_csv(r'C:\Users\HP\Desktop\pandas\adv-datasets\shoppingmall.csv')
cust

      ID  Gender  Age  Income  Score
0      1    Male   19      15     39
1      2    Male   21      15     81
2      3  Female   20      16      6
3      4  Female   23      16     77
4      5  Female   31      17     40
..   ...     ...  ...     ...    ...
195  196  Female   35     120     79
196  197  Female   45     126     28
197  198    Male   32     126     74
198  199    Male   32     137     18
199  200    Male   30     137     83

[200 rows x 5 columns]

In [4]:
shop = pd.read_csv(r'C:\Users\HP\Desktop\pandas\adv-datasets\shopping_customers.csv')
shop

     ID  Gender  Age  Income  Score
0   201    Male   61      31     39
1   202    Male   63      31     81
2   203  Female   59      23      6
3   204  Female   37      23     77
4   205  Female   45      19     40
5   206  Female   47      19     76
6   207  Female   55      32      6
7   208  Female   23      24     94
8   209    Male   28      25      3
9   210  Female   29      17     72
10  211    Male   41      18     14
11  212  Female   20      19     99
12  213  Female   59      21     15
13  214  Female   53      22     77
14  215    Male   48      22     13
15  216    Male   64      26     79
16  217  Female   67      26     35
17  218    Male   67      27     66
18  219    Male   20      28     29
19  220  Female   23      24     98

In [6]:
#  select * from cust where income > 50 UNION ALL
# select * from shop where income < 45
pd.concat([cust[cust.Income > 50], shop[shop.Income > 45]])

      ID  Gender  Age  Income  Score
74    75    Male   59      54     47
75    76    Male   26      54     54
76    77  Female   45      54     53
77    78    Male   40      54     48
78    79  Female   23      54     52
..   ...     ...  ...     ...    ...
195  196  Female   35     120     79
196  197  Female   45     126     28
197  198    Male   32     126     74
198  199    Male   32     137     18
199  200    Male   30     137     83

[126 rows x 5 columns]

In [7]:
pd.concat([cust[cust.Income > 50], shop[shop.Income > 45]]).drop_duplicates()

      ID  Gender  Age  Income  Score
74    75    Male   59      54     47
75    76    Male   26      54     54
76    77  Female   45      54     53
77    78    Male   40      54     48
78    79  Female   23      54     52
..   ...     ...  ...     ...    ...
195  196  Female   35     120     79
196  197  Female   45     126     28
197  198    Male   32     126     74
198  199    Male   32     137     18
199  200    Male   30     137     83

[126 rows x 5 columns]

In [8]:
cust.head()

   ID  Gender  Age  Income  Score
0   1    Male   19      15     39
1   2    Male   21      15     81
2   3  Female   20      16      6
3   4  Female   23      16     77
4   5  Female   31      17     40

In [17]:
# insert a new row at the top of the DataFrame `cust`
cust.loc[200]=[500, 'Male', 50, 30, 20]
cust

       ID  Gender  Age  Income  Score
 0      1    Male   19      15     39
 1      2    Male   21      15     81
 2      3  Female   20      16      6
 3      4  Female   23      16     77
 4      5  Female   31      17     40
...   ...     ...  ...     ...    ...
 197  198    Male   32     126     74
 198  199    Male   32     137     18
 199  200    Male   30     137     83
-1    500    Male   50      30     20
 200  500    Male   50      30     20

[202 rows x 5 columns]

In [20]:
# update cust set score = 11 where score = 10
cust.loc[cust['Score'] == 10, 'Score'] == 11

138    False
172    False
Name: Score, dtype: bool

In [21]:
cust[cust.Score==11]

      ID Gender  Age  Income  Score
128  129   Male   59      71     11

In [28]:
# delete from cust where score = 11
cust = cust.drop(cust[cust.Score == 11].index)

In [29]:
cust[cust.Score == 11]

Empty DataFrame
Columns: [ID, Gender, Age, Income, Score]
Index: []