groupby() method -> to split the data into groups and then apply any operation on groups

In [2]:
import pandas as pd

ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

In [3]:
df = pd.read_csv(r'C:\Users\HP\Desktop\pandas\adv-datasets\cities_weather.csv')
df

           day      city  temperature  windspeed   event
0   01-01-2017  new york           32          6    Rain
1   01-02-2017  new york           36          7   Sunny
2   01-03-2017  new york           28         12    Snow
3   01-04-2017  new york           33          7   Sunny
4   01-01-2017    mumbai           90          5   Sunny
5   01-02-2017    mumbai           85         12     Fog
6   01-03-2017    mumbai           87         15     Fog
7   01-04-2017    mumbai           92          5    Rain
8   01-01-2017     paris           45         20   Sunny
9   01-02-2017     paris           50         13  Cloudy
10  01-03-2017     paris           54          8  Cloudy
11  01-04-2017     paris           42         10  Cloudy

In [4]:
df1 = df.groupby('city')

In [5]:
for city, city_df in df1:
    print(city_df)

          day    city  temperature  windspeed  event
4  01-01-2017  mumbai           90          5  Sunny
5  01-02-2017  mumbai           85         12    Fog
6  01-03-2017  mumbai           87         15    Fog
7  01-04-2017  mumbai           92          5   Rain
          day      city  temperature  windspeed  event
0  01-01-2017  new york           32          6   Rain
1  01-02-2017  new york           36          7  Sunny
2  01-03-2017  new york           28         12   Snow
3  01-04-2017  new york           33          7  Sunny
           day   city  temperature  windspeed   event
8   01-01-2017  paris           45         20   Sunny
9   01-02-2017  paris           50         13  Cloudy
10  01-03-2017  paris           54          8  Cloudy
11  01-04-2017  paris           42         10  Cloudy

In [6]:
df1.get_group('mumbai')

          day    city  temperature  windspeed  event
4  01-01-2017  mumbai           90          5  Sunny
5  01-02-2017  mumbai           85         12    Fog
6  01-03-2017  mumbai           87         15    Fog
7  01-04-2017  mumbai           92          5   Rain

Aggregate function : are the function that act on group of element
    max(), min(), mean(), sum(), median(), std(), prod(), count()

In [7]:
df2 = df1.get_group('mumbai')
# df1.get_group('mumbai').max()

In [8]:
df2.agg('max')

day            01-04-2017
city               mumbai
temperature            92
windspeed              15
event               Sunny
dtype: object

In [9]:
df2['temperature'].agg(['max', 'min'])

max    92
min    85
Name: temperature, dtype: int64

In [13]:
# find avg speed in New york
df1 = df.groupby('city')['windspeed'].mean()
df1

city
mumbai       9.25
new york     8.00
paris       12.75
Name: windspeed, dtype: float64

In [ ]:
df2 = df1.get_group('new york')
print('Avg new york windspeed: ',df2['windspeed'].agg('mean'))

Avg new york windspeed:  8.0

In [ ]:
# min temp and max windspeed in new york
df2 = df1.get_group('new york')
print('minimum in tempreature in new york: ',df2['temperature'].agg('min'))
print('maximum in tempreature in new york: ',df2['windspeed'].agg('max'))

minimum in tempreature in new york:  28
maximum in tempreature in new york:  12

In [ ]:
# 2nd way
df2.agg({'temperature' : 'min', 'windspeed': 'max'})

temperature    28
windspeed      12
dtype: int64

In [ ]:
#  find min, max on temperature - sum and avg on windspeed in new york
df2.agg({'temperature' : ['min', 'max'], 'windspeed' : ['sum', 'mean']})

      temperature  windspeed
min          28.0        NaN
max          36.0        NaN
sum           NaN       32.0
mean          NaN        8.0

In [19]:
df[df['city'] == 'new york'].agg({
    'temperature': ['min', 'max'],
    'windspeed': ['sum', 'mean']
})

      temperature  windspeed
min          28.0        NaN
max          36.0        NaN
sum           NaN       32.0
mean          NaN        8.0

In [ ]:
# its for total dataset
df.agg({'temperature' : ['min', 'max'], 'windspeed' : ['sum', 'mean']})

      temperature  windspeed
min          28.0        NaN
max          92.0        NaN
sum           NaN      120.0
mean          NaN       10.0