In [2]:
import pandas as pd

In [4]:
df = pd.read_csv(r'C:\Users\HP\Desktop\pandas\adv_dataset\carprices.csv')
df

                car model  mileage  sale price  age  model_date
0                  BMW X5    69000       18000    6  12-12-2000
1                  BMW X5    35000       34000    3  01-10-2000
2                  BMW X5    57000       26100    5  12-05-1995
3                  BMW X5    22500       40000    2  20-05-1994
4                  BMW X5    46000       31500    4  05-05-1992
5                 Audi A5    59000       29400    5  10-10-2002
6                 Audi A5    52000       32000    5  10-10-2002
7                 Audi A5    72000       19300    6  25-05-2001
8                 Audi A5    91000       12000    8  15-09-1997
9   Mercedez Benz C class    67000       22000    6  14-09-1998
10  Mercedez Benz C class    83000       20000    7  09-09-1996
11  Mercedez Benz C class    79000       21000    7  08-09-1999
12  Mercedez Benz C class    59000       33000    5  09-09-2004

In [13]:
df.filter(regex='a', axis=1)

                car model  mileage  sale price  age  model_date
0                  BMW X5    69000       18000    6  12-12-2000
1                  BMW X5    35000       34000    3  01-10-2000
2                  BMW X5    57000       26100    5  12-05-1995
3                  BMW X5    22500       40000    2  20-05-1994
4                  BMW X5    46000       31500    4  05-05-1992
5                 Audi A5    59000       29400    5  10-10-2002
6                 Audi A5    52000       32000    5  10-10-2002
7                 Audi A5    72000       19300    6  25-05-2001
8                 Audi A5    91000       12000    8  15-09-1997
9   Mercedez Benz C class    67000       22000    6  14-09-1998
10  Mercedez Benz C class    83000       20000    7  09-09-1996
11  Mercedez Benz C class    79000       21000    7  08-09-1999
12  Mercedez Benz C class    59000       33000    5  09-09-2004

In [ ]:
# display columns that end with 'age'
df.filter(regex='age$', axis=1)

    mileage  age
0     69000    6
1     35000    3
2     57000    5
3     22500    2
4     46000    4
5     59000    5
6     52000    5
7     72000    6
8     91000    8
9     67000    6
10    83000    7
11    79000    7
12    59000    5

In [8]:
df_car = df['car model']
df_car.str.len()

0      6
1      6
2      6
3      6
4      6
5      7
6      7
7      7
8      7
9     21
10    21
11    21
12    21
Name: car model, dtype: int64

In [9]:
df_car.str.len()

0      6
1      6
2      6
3      6
4      6
5      7
6      7
7      7
8      7
9     21
10    21
11    21
12    21
Name: car model, dtype: int64

In [11]:
# retive the records where only 'audi' is found
df[df_car.str.contains(r'Audi')]

  car model  mileage  sale price  age  model_date
5   Audi A5    59000       29400    5  10-10-2002
6   Audi A5    52000       32000    5  10-10-2002
7   Audi A5    72000       19300    6  25-05-2001
8   Audi A5    91000       12000    8  15-09-1997

In [15]:
df_car.str.replace(r'Audi', 'Bodi')

0                    BMW X5
1                    BMW X5
2                    BMW X5
3                    BMW X5
4                    BMW X5
5                   Bodi A5
6                   Bodi A5
7                   Bodi A5
8                   Bodi A5
9     Mercedez Benz C class
10    Mercedez Benz C class
11    Mercedez Benz C class
12    Mercedez Benz C class
Name: car model, dtype: object

In [19]:
x = df_car.str.extract(r'(BMW \w\w)')
x.dropna()

        0
0  BMW X5
1  BMW X5
2  BMW X5
3  BMW X5
4  BMW X5

In [22]:
lst = df_car.str.split(r'[XA]\d')
for i in lst : print(i)

['BMW ', '']
['BMW ', '']
['BMW ', '']
['BMW ', '']
['BMW ', '']
['Audi ', '']
['Audi ', '']
['Audi ', '']
['Audi ', '']
['Mercedez Benz C class']
['Mercedez Benz C class']
['Mercedez Benz C class']
['Mercedez Benz C class']

In [25]:
# retive only year
df['model_date'].str.findall(r'\d\d-\d\d-(\d\d\d\d)')

0     [2000]
1     [2000]
2     [1995]
3     [1994]
4     [1992]
5     [2002]
6     [2002]
7     [2001]
8     [1997]
9     [1998]
10    [1996]
11    [1999]
12    [2004]
Name: model_date, dtype: object

In [26]:
df['model_date'].str.findall(r'(\d\d)-\d\d-(\d\d\d\d)')

0     [(12, 2000)]
1     [(01, 2000)]
2     [(12, 1995)]
3     [(20, 1994)]
4     [(05, 1992)]
5     [(10, 2002)]
6     [(10, 2002)]
7     [(25, 2001)]
8     [(15, 1997)]
9     [(14, 1998)]
10    [(09, 1996)]
11    [(08, 1999)]
12    [(09, 2004)]
Name: model_date, dtype: object