In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\Users\HP\Desktop\pandas\adv_dataset\AAPL Data1.csv')
df

     Open   High    Low  Close     Volume
0   61.13  61.20  60.45  60.90   17916255
1   60.79  61.68  60.72  61.65   18369296
2   61.86  62.31  61.68  62.26   24143241
3   62.24  62.44  60.64  60.82   35709867
4   61.19  61.33  60.30  60.82   31130522
..    ...    ...    ...    ...        ...
95  63.99  67.50  62.00  62.06  104618517
96  66.22  69.98  63.24  69.49   92683032
97  60.49  64.77  60.00  60.55   80605865
98  61.88  64.40  59.60  63.22   81013965
99  59.94  62.50  59.28  61.67   75058406

[100 rows x 5 columns]

In [7]:
rng = pd.date_range(start='2020/1/20', periods=100, freq='B')
rng

DatetimeIndex(['2020-01-20', '2020-01-21', '2020-01-22', '2020-01-23',
               '2020-01-24', '2020-01-27', '2020-01-28', '2020-01-29',
               '2020-01-30', '2020-01-31', '2020-02-03', '2020-02-04',
               '2020-02-05', '2020-02-06', '2020-02-07', '2020-02-10',
               '2020-02-11', '2020-02-12', '2020-02-13', '2020-02-14',
               '2020-02-17', '2020-02-18', '2020-02-19', '2020-02-20',
               '2020-02-21', '2020-02-24', '2020-02-25', '2020-02-26',
               '2020-02-27', '2020-02-28', '2020-03-02', '2020-03-03',
               '2020-03-04', '2020-03-05', '2020-03-06', '2020-03-09',
               '2020-03-10', '2020-03-11', '2020-03-12', '2020-03-13',
               '2020-03-16', '2020-03-17', '2020-03-18', '2020-03-19',
               '2020-03-20', '2020-03-23', '2020-03-24', '2020-03-25',
               '2020-03-26', '2020-03-27', '2020-03-30', '2020-03-31',
               '2020-04-01', '2020-04-02', '2020-04-03', '2020-04-06',
               '2020-04-07', '2020-04-08', '2020-04-09', '2020-04-10',
               '2020-04-13', '2020-04-14', '2020-04-15', '2020-04-16',
               '2020-04-17', '2020-04-20', '2020-04-21', '2020-04-22',
               '2020-04-23', '2020-04-24', '2020-04-27', '2020-04-28',
               '2020-04-29', '2020-04-30', '2020-05-01', '2020-05-04',
               '2020-05-05', '2020-05-06', '2020-05-07', '2020-05-08',
               '2020-05-11', '2020-05-12', '2020-05-13', '2020-05-14',
               '2020-05-15', '2020-05-18', '2020-05-19', '2020-05-20',
               '2020-05-21', '2020-05-22', '2020-05-25', '2020-05-26',
               '2020-05-27', '2020-05-28', '2020-05-29', '2020-06-01',
               '2020-06-02', '2020-06-03', '2020-06-04', '2020-06-05'],
              dtype='datetime64[ns]', freq='B')

In [8]:
df.set_index(rng, inplace=True)
df

             Open   High    Low  Close     Volume
2020-01-20  61.13  61.20  60.45  60.90   17916255
2020-01-21  60.79  61.68  60.72  61.65   18369296
2020-01-22  61.86  62.31  61.68  62.26   24143241
2020-01-23  62.24  62.44  60.64  60.82   35709867
2020-01-24  61.19  61.33  60.30  60.82   31130522
...           ...    ...    ...    ...        ...
2020-06-01  63.99  67.50  62.00  62.06  104618517
2020-06-02  66.22  69.98  63.24  69.49   92683032
2020-06-03  60.49  64.77  60.00  60.55   80605865
2020-06-04  61.88  64.40  59.60  63.22   81013965
2020-06-05  59.94  62.50  59.28  61.67   75058406

[100 rows x 5 columns]

In [9]:
df.asfreq('D', method='pad')

             Open   High    Low  Close     Volume
2020-01-20  61.13  61.20  60.45  60.90   17916255
2020-01-21  60.79  61.68  60.72  61.65   18369296
2020-01-22  61.86  62.31  61.68  62.26   24143241
2020-01-23  62.24  62.44  60.64  60.82   35709867
2020-01-24  61.19  61.33  60.30  60.82   31130522
...           ...    ...    ...    ...        ...
2020-06-01  63.99  67.50  62.00  62.06  104618517
2020-06-02  66.22  69.98  63.24  69.49   92683032
2020-06-03  60.49  64.77  60.00  60.55   80605865
2020-06-04  61.88  64.40  59.60  63.22   81013965
2020-06-05  59.94  62.50  59.28  61.67   75058406

[138 rows x 5 columns]