window -> one or more col of a df,
window func -> time series

In [2]:
import pandas as pd
import numpy as np

In [6]:
df = pd.DataFrame({
    'a': [1, 2, 34, 5, 6, 7, 8],
    'b': [10, np.nan, np.nan, 20, np.nan, np.nan, 30]
})

print(df)

    a     b
0   1  10.0
1   2   NaN
2  34   NaN
3   5  20.0
4   6   NaN
5   7   NaN
6   8  30.0

In [7]:
# find cummulative sum of the col 'a'
df['a_cumsum'] = df['a'].cumsum()
df

    a     b  a_cumsum
0   1  10.0         1
1   2   NaN         3
2  34   NaN        37
3   5  20.0        42
4   6   NaN        48
5   7   NaN        55
6   8  30.0        63

In [12]:
# cummu prod of 'a'
df['a_cumprod'] = df['a'].cumprod()
df

    a     b  a_cumsum  a_cumprod
0   1  10.0         1          1
1   2   NaN         2          2
2  34   NaN        68         68
3   5  20.0       340        340
4   6   NaN      2040       2040
5   7   NaN     14280      14280
6   8  30.0    114240     114240

Rolling window: means moving window

In [15]:
# rolling window to find rolling sum of 'a'
obj = df['a'].rolling(window = 2)
df['a_roll_sum'] = obj.sum()
df

    a     b  a_cumsum  a_cumprod  a_roll_sum
0   1  10.0         1          1         NaN
1   2   NaN         2          2         3.0
2  34   NaN        68         68        36.0
3   5  20.0       340        340        39.0
4   6   NaN      2040       2040        11.0
5   7   NaN     14280      14280        13.0
6   8  30.0    114240     114240        15.0

In [16]:
# find rolling count on col b
obj = df['b'].rolling(window = 2, min_periods=2)
df['b_roll_cnt'] = obj.count()
df

    a     b  a_cumsum  a_cumprod  a_roll_sum  b_roll_cnt
0   1  10.0         1          1         NaN         NaN
1   2   NaN         2          2         3.0         1.0
2  34   NaN        68         68        36.0         0.0
3   5  20.0       340        340        39.0         1.0
4   6   NaN      2040       2040        11.0         1.0
5   7   NaN     14280      14280        13.0         0.0
6   8  30.0    114240     114240        15.0         1.0

cummulative nd expandind window are same

In [17]:
# find mean val on expanding window
obj = df['a'].expanding(min_periods=1)
df['a_exp_mean'] = obj.mean()
df

    a     b  a_cumsum  a_cumprod  a_roll_sum  b_roll_cnt  a_exp_mean
0   1  10.0         1          1         NaN         NaN    1.000000
1   2   NaN         2          2         3.0         1.0    1.500000
2  34   NaN        68         68        36.0         0.0   12.333333
3   5  20.0       340        340        39.0         1.0   10.500000
4   6   NaN      2040       2040        11.0         1.0    9.600000
5   7   NaN     14280      14280        13.0         0.0    9.166667
6   8  30.0    114240     114240        15.0         1.0    9.000000