In [7]:
import pandas as pd

In [8]:
tpl = ((1001, 'Tushar'), (1002, 'Satyarth'), (1003, 'Rohit'), (1004, 'Shivam'))

In [9]:
df = pd.DataFrame(tpl, columns=['col1', 'col2'])
df

   col1      col2
0  1001    Tushar
1  1002  Satyarth
2  1003     Rohit
3  1004    Shivam

In [10]:
#  rename the col
df.rename(columns = {'col1' : 'empid', 'col2' : 'name'}, inplace=True)
df

   empid      name
0   1001    Tushar
1   1002  Satyarth
2   1003     Rohit
3   1004    Shivam

In [11]:
# add third col or new col
df['dept'] = ['IT', 'HR', 'Finance', 'Admin']
df

   empid      name     dept
0   1001    Tushar       IT
1   1002  Satyarth       HR
2   1003     Rohit  Finance
3   1004    Shivam    Admin

In [12]:
#  how to insert new col in betw existing col
df.insert(loc=1, column = 'salary', value = [35000, 22000, 50000, 54001])

In [13]:
df

   empid  salary      name     dept
0   1001   35000    Tushar       IT
1   1002   22000  Satyarth       HR
2   1003   50000     Rohit  Finance
3   1004   54001    Shivam    Admin

In [14]:
#  iosert phone number col in betw name and dept col
df.insert(loc=3, column = 'phone', value = [1234567890, 9876543210, 4567891230, 7891234560])
df

   empid  salary      name       phone     dept
0   1001   35000    Tushar  1234567890       IT
1   1002   22000  Satyarth  9876543210       HR
2   1003   50000     Rohit  4567891230  Finance
3   1004   54001    Shivam  7891234560    Admin

In [15]:
#  create a new col from existing col
df['Tax'] = df['salary'] * 10/100
df

   empid  salary      name       phone     dept     Tax
0   1001   35000    Tushar  1234567890       IT  3500.0
1   1002   22000  Satyarth  9876543210       HR  2200.0
2   1003   50000     Rohit  4567891230  Finance  5000.0
3   1004   54001    Shivam  7891234560    Admin  5400.1

In [16]:
#  create a new col from exiting col using lambda
df1 = df.assign( PF = lambda x : x.salary * 12.5/100)
df1

   empid  salary      name       phone     dept     Tax        PF
0   1001   35000    Tushar  1234567890       IT  3500.0  4375.000
1   1002   22000  Satyarth  9876543210       HR  2200.0  2750.000
2   1003   50000     Rohit  4567891230  Finance  5000.0  6250.000
3   1004   54001    Shivam  7891234560    Admin  5400.1  6750.125

In [21]:
# cal net salary net sal = salary - tax - pf
df2 = df1.assign(net_salary = lambda x : x.salary - x.Tax - x.PF)
df2

   empid  salary      name       phone     dept     Tax        PF  net_salary
0   1001   35000    Tushar  1234567890       IT  3500.0  4375.000   27125.000
1   1002   22000  Satyarth  9876543210       HR  2200.0  2750.000   17050.000
2   1003   50000     Rohit  4567891230  Finance  5000.0  6250.000   38750.000
3   1004   54001    Shivam  7891234560    Admin  5400.1  6750.125   41850.775

In [ ]:
#  cal deduction = tax + pf
df3 = df2.assign(deductions = lambda x : x.Tax + x.PF)
df3

,empid,salary,name,phone,dept,Tax,PF,net_salary,deductions
0,1001,35000,Tushar,1234567890,IT,3500.0,4375.000,27125.000,7875.000
1,1002,22000,Satyarth,9876543210,HR,2200.0,2750.000,17050.000,4950.000
2,1003,50000,Rohit,4567891230,Finance,5000.0,6250.000,38750.000,11250.000
3,1004,54001,Shivam,7891234560,Admin,5400.1,6750.125,41850.775,12150.225